### ISSUE TITLE
Booker Helper & Mysql Connection

### ISSUE THREAD

**Issue by S1MP50N** [mjoycemilburn/barbershop#1]
Hi, 
Thanks for sharing your booking code. Could you please share booker_helper.php and connect_ecommerce_prototype.php? If not any information on how they function or stubbed content would be appreciated. Looking at helping out a friend and this could be a great leg up.

**Comment by mjoycemilburn** [comment]
Thanks for your interest. Booker_helpers.php is in the php folder. In its
simplest form, connect_ecommerce_prototype.php is just a conventional php
connect - eg $con = mysqli_connect('localhost', 'root', 'password',
'db_name');

I'll be releasing a major upgrade in the next few days. The code currently
on Github is fine but lacks many useful features. You might want to hang
fire before doing too much.

MartinJ

**Comment by S1MP50N** [comment]
Hi Martin,

Thanks for the quick response 👍 booker_helpers.php appears to be empty on here.. at least appears to be, unless I am doing something stupid :) Excellent on the connect_ecommerce_prototype, I had hoped it was as simple as that but wanted to check. 

I will hold off doing anything too crazy with the hope you update in the next few days. 

Thanks again for sharing. 

Shaun

**Comment by mjoycemilburn** [comment]
Rats - seems I fouled up there somehow. Thanks for picking my error up. My
current version of booker_helpers may not be compatible with the rest of
the code on Github, but I've restored a version that I /think/ should work.
It won't be far out, anyway and should tide you over till I get the new
suite out.

Regards, MJ

**Comment by S1MP50N** [comment]
Much appreciated. I will give it a shot and see how I go. :)

Thanks,
Shaun
